runtime: python39  # because you're using Python
env: flex  # use the flexible environment

entrypoint: streamlit run --server.port $PORT --server.enableCORS false app.py

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

resources:
  cpu: 64
  memory_gb: 16
  disk_size_gb: 15
