runtime: python39  # because you're using Python
instance_class: F2  # select a class based on your needs
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
entrypoint: streamlit run --server.port $PORT --server.enableCORS false app.py
